//
//  MathematicsData.swift
//  MathematicsFact
//
//  Created by Kevin Jonathan on 30/05/21.
//

import Foundation
import UIKit
 
var mathematicsTypes: [MathematicsType] = [
    MathematicsType(photo: UIImage(named: "algebra")!, name: "Algebra", description: "Algebra includes the study of algebraic structures, which are sets and operations defined on these sets satisfying certain axioms. The field of algebra is further divided according to which structure is studied; for instance, group theory concerns an algebraic structure called group."),
    MathematicsType(photo: UIImage(named: "calculus")!, name: "Calculus and Analysis", description: "Calculus studies the computation of limits, derivatives, and integrals of functions of real numbers, and in particular studies instantaneous rates of change. Analysis evolved from calculus."),
    MathematicsType(photo: UIImage(named: "geometry")!, name: "Geometry and Topology", description: "Geometry is initially the study of spatial figures like circles and cubes, though it has been generalized considerably. Topology developed from geometry; it looks at those properties that do not change even when the figures are deformed by stretching and bending, like dimension."),
    MathematicsType(photo: UIImage(named: "combinatorics")!, name: "Combinatorics", description: "Combinatorics concerns the study of discrete (and usually finite) objects. Aspects include \"counting\" the objects satisfying certain criteria (enumerative combinatorics), deciding when the criteria can be met, and constructing and analyzing objects meeting the criteria (as in combinatorial designs and matroid theory), finding \"largest\", \"smallest\", or \"optimal\" objects (extremal combinatorics and combinatorial optimization), and finding algebraic structures these objects may have (algebraic combinatorics)."),
    MathematicsType(photo: UIImage(named: "logic")!, name: "Logic", description: "Logic is the foundation which underlies mathematical logic and the rest of mathematics. It tries to formalize valid reasoning. In particular, it attempts to define what constitutes a proof."),
    MathematicsType(photo: UIImage(named: "number_theory")!, name: "Number Theory", description: "The branch of mathematics that deals with the properties and relationships of numbers, especially the positive integers. Number theory is a branch of pure mathematics devoted primarily to the study of the integers and integer-valued functions. German mathematician Carl Friedrich Gauss said, \"Mathematics is the queen of the sciences—and number theory is the queen of mathematics.\" Number theory also studies the natural, or whole, numbers. One of the central concepts in number theory is that of the prime number, and there are many questions about primes that appear simple but whose resolution continues to elude mathematicians."),
    MathematicsType(photo: UIImage(named: "dynamical_system")!, name: "Dynamical Systems and Differential Equations", description: "A differential equation is an equation involving an unknown function and its derivatives. In a dynamical system, a fixed rule describes the time dependence of a point in a geometrical space. The mathematical models used to describe the swinging of a clock pendulum, the flow of water in a pipe, or the number of fish each spring in a lake are examples of dynamical systems."),
    MathematicsType(photo: UIImage(named: "mathematical_physics")!, name: "Mathematical Physics", description: "Mathematical physics is concerned with \"the application of mathematics to problems in physics and the development of mathematical methods suitable for such applications and for the formulation of physical theories\"."),
    MathematicsType(photo: UIImage(named: "theory_computation")!, name: "Theory of Computation", description: "The fields of mathematics and computing intersect both in computer science, the study of algorithms and data structures, and in scientific computing, the study of algorithmic methods for solving problems in mathematics, science and engineering."),
    MathematicsType(photo: UIImage(named: "information_theory")!, name: "Information Theory and Signal Processing", description: "Information theory is a branch of applied mathematics and Social science involving the quantification of information. Historically, information theory was developed to find fundamental limits on compressing and reliably communicating data. Signal processing is the analysis, interpretation, and manipulation of signals. Signals of interest include sound, images, biological signals such as ECG, radar signals, and many others. Processing of such signals includes filtering, storage and reconstruction, separation of information from noise, compression, and feature extraction."),
    MathematicsType(photo: UIImage(named: "probability")!, name: "Probability and Statistics", description: "Probability theory is the formalization and study of the mathematics of uncertain events or knowledge. The related field of mathematical statistics develops statistical theory with mathematics. Statistics, the science concerned with collecting and analyzing data, is an autonomous discipline (and not a subdiscipline of applied mathematics)."),
    MathematicsType(photo: UIImage(named: "game_theory")!, name: "Game Theory", description: "Game theory is a branch of mathematics that uses models to study interactions with formalized incentive structures (\"games\"). It has applications in a variety of fields, including economics, anthropology , political science, social psychology and military strategy."),
    MathematicsType(photo: UIImage(named: "operations_research")!, name: "Operations Research", description: "Operations research is the study and use of mathematical models, statistics and algorithms to aid in decision-making, typically with the goal of improving or optimizing performance of real-world systems."),
]
